### PR TITLE
Add GH actions

### PR DESCRIPTION
**Pull request by cooper667**
# Description

Add lint and test on push

Also lint the existing files

One of the main changes is any updates to state that use the _previous_ state are now in callbacks.

Also moved theme to it's own file rather than part of UI as that causes circular dependencies

Deps:

Adds the required ES Lint plugins to work nicely with React and TSX

### CODE REVIEW

**Review by philipjackson — DISMISSED** [review]

**Comment by cooper667** [comment]
I have 1 left I can't fix (it's a TS error not lint tho so not sure how it got thro):


```typescript
  handleSliderChange = (state: string) => (
    event: ChangeEvent,
    value: number
  ): void => {
    this.setState({ [state]: value });
  };
  ```

apparently we can't use `[state]` there, but not sure why?

**Comment by ChasNelson1990** [comment]
What's the actual error?

**Comment by cooper667** [comment]
```
[tsl] ERROR in /home/runner/work/annotate/annotate/src/ui.tsx(348,19)
      TS2345: Argument of type '{ [x: string]: number; }' is not assignable to parameter of type 'State | ((prevState: Readonly<State>, props: Readonly<any>) => State | Pick<State, keyof State>) | Pick<State, keyof State>'.
  Type '{ [x: string]: number; }' is missing the following properties from type 'Pick<State, keyof State>': scaleAndPan, imageWidth, imageHeight, activeAnnotationID, and 6 more.
 @ ./src/index.tsx 3:0-37 4:36-49```

**Comment by cooper667** [comment]
> I have 1 left I can't fix (it's a TS error not lint tho so not sure how it got thro):
> 
> ```ts
>   handleSliderChange = (state: string) => (
>     event: ChangeEvent,
>     value: number
>   ): void => {
>     this.setState({ [state]: value });
>   };
> ```
> 
> apparently we can't use `[state]` there, but not sure why?

@SilviaZeta you got any idea for this?

**Comment by ChasNelson1990** [comment]
If we make the type `Pick<keyof State>` on the input does that not work?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Pull request merged**
