### PR TITLE
feat: Re-group tools and fix text input triggers shortcuts

### LINKED ISSUE #239: Move Select and Annotation Label button
No problem, possible layout improvement for functionality.

Solution to move the "Select" button and "Annotation Label" button to the same button block as "Add New Annotation" and "Clear Annotation" to create a single annotation management block of buttons.

Alternative to leave as is would be fine, functionality is not affected, more aesthetic and process flow. Might be worth considering (as well) splitting the image control buttons (Brightness, Contrast, Channels) into a separate block from the functionality buttons?

Initial discussion with Chas, no firm decision.

### PR DESCRIPTION
**Pull request by SilviaZeta**
# Description

- re-group tools in toolbars
- fix shortcuts triggered when inputting a new label

closes #239

# Dependency changes
No

# Testing
No

# Documentation
No

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
I really like this but would like @joshuajames-smith to give some input and thoughts before we merge please

**Comment by joshuajames-smith** [comment]
I quite like the new groupings of the tools! Think it really makes sense with the number of tools we have that we can group them more by their functionality. 
Might be something to create another issue for, it is also likely just my computer but the toolbars seem really big and are overlapping each other?
annotate screenshot for review


Most of the shortcut key assignments are working great too! I have just noticed a couple that seems to not work for me or I think would help the users: 
- [ ] Tapping A once actives the 'Select' tool but tapping A once again then actives the 'Brush' tool as if it is toggling between them, not sure if this is meant to happen? 
- [ ] The 'Contrast' tools shortcut is \ but for me pressing that key seems to not active the tool?
- [ ] There's been some change to the mini-map shortcuts so that CTRL becomes ALT as CTRL is already assigned to most browser shortcut interactions. The 'Zoom-In', 'Zoom-Out' and 'Fit to Page' tools in the opened mini-map window is still CTRL and I think it be would be great if these could be ALT too? Keeping the second shortcut key the same.
- [ ] To download annotations, the shortcut 'D' works! Not sure if the upload annotations with shortcut 'U' is working, however?

**Review by philipjackson — APPROVED** [review]

**Comment by SilviaZeta** [comment]
Thanks for the feedback! I've added some comments.

> I quite like the new groupings of the tools! Think it really makes sense with the number of tools we have that we can group them more by their functionality.

Thanks, it was @philhallbio's idea. 

> Might be something to create another issue for, it is also likely just my computer but the toolbars seem really big and are overlapping each other?

I agree, the toolbars look big with 100% zoom. The size of the icon buttons and the spacing between them haven't changed, so I think the extra space is taken by the start and end of each toolbar. Yes, I also think this could go in a new issue.

> annotate screenshot for review
> 
> Most of the shortcut key assignments are working great too! I have just noticed a couple that seems to not work for me or I think would help the users:
> 
>     * [ ]  Tapping A once actives the 'Select' tool but tapping A once again then actives the 'Brush' tool as if it is toggling between them, not sure if this is meant to happen?

Yes, i think he idea was for the 'select' button to work as a toggle.
> 
>     * [ ]  The 'Contrast' tools shortcut is \ but for me pressing that key seems to not active the tool?
Ok, which browser are you using?

>     * [ ]  There's been some change to the mini-map shortcuts so that CTRL becomes ALT as CTRL is already assigned to most browser shortcut interactions. The 'Zoom-In', 'Zoom-Out' and 'Fit to Page' tools in the opened mini-map window is still CTRL and I think it be would be great if these could be ALT too? Keeping the second shortcut key the same.
> 
Sure, we can replace these shortcuts. We can use 'alt ]' for 'fit to page', though 'alt +' and 'alt -' are already taken by 'minimise map' and 'maximise map', so we would need new shortcuts for 'zoom-in' and 'zoom-out', i think?

>     * [ ]  To download annotations, the shortcut 'D' works! Not sure if the upload annotations with shortcut 'U' is working, however?
That's right, the 'u' shortcut is still missing. I haven't gotten around to doing that one yet.

**Comment by joshuajames-smith** [comment]
> Ok, which browser are you using?

I am using Google Chrome Version 91.0.4472.114 (64-bit).

> Sure, we can replace these shortcuts. We can use 'alt ]' for 'fit to page', though 'alt +' and 'alt -' are already taken by 'minimise map' and 'maximise map', so we would need new shortcuts for 'zoom-in' and 'zoom-out', i think?
So this option would let us use alt exclusively for the map tools in annotate:
- Minimise Map = 'alt -'
-  Maximise Map = 'alt +'
- Zoom-in = 'alt 1'
- Zoom-out = 'alt 2'
- Fit to Page = 'alt 3'

Or if we didn't think the numbers would work, we could look at this potential option of using alt and shift for the map controls:
- Minimise Map = 'alt -'
-  Maximise Map = 'alt +'
- Zoom-in = 'shft +'
- Zoom-out = 'shft -'
- Fit to Page = 'shift 0' / 'alt ]'

**Comment by SilviaZeta** [comment]
Ok, I've changed the shortcuts according to your first suggestion. Not sure why the 'contrast' shortcut doesn't work for you though, as it works for me with same browser and version. Perhaps it's worth opening an issue to see if anyone can reproduce the bug.

**Review by ChasNelson1990 — APPROVED** [review]

**Comment by philipjackson** [comment]
> Not sure why the 'contrast' shortcut doesn't work for you though, as it works for me with same browser and version. Perhaps it's worth opening an issue to see if anyone can reproduce the bug.

Contrast shortcut doesn't work for me either FYI (Linux, Firefox). Maybe it's because "\" is kind of a special character?

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
