### PR TITLE
feat: position BaseSlider not to hide under upload/download buttons wh…

### PR DESCRIPTION
**Pull request by ChrisBaidoo**
## Description

Position BaseSlider so that it doesn't hide under upload/download buttons when rendered in Dominate

## Dependency changes
N/A

## Testing

N/A

## Documentation

N/A

## Migrations (if applicable)

N/A

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

**Comment by ChrisBaidoo** [comment]
Screenshot 2021-08-19 at 14 37 33

**Comment by ChasNelson1990** [comment]
Wait, why is the slider on the right hand side for dominate? surely it should appear on the left, like in the standalone app?

**Comment by ChrisBaidoo** [comment]
> Wait, why is the slider on the right hand side for dominate? surely it should appear on the left, like in the standalone app?

Hmmm, last time I checked it was on the right in the standalone app, unless Im missing something. 
As you'll see from the commit in this PR all I did was increase the top and right values to 180px and 18px respectively.

Screenshot 2021-08-19 at 17 19 15

**Comment by ChasNelson1990** [comment]
Erm, what is that a slider for?! None of them should go to 1081?!?!! Also, that is not there on the link above?!

**Review by philipjackson — APPROVED** [review]

**Comment by ChasNelson1990** [comment]
So, turns out, this is the z slider which should never have been styled like the other sliders.

**Review by ChasNelson1990 — APPROVED** [review]

**Comment by ChasNelson1990** [comment]
Pulled on CBs behalf

**Pull request merged**
