### PR TITLE
Select anything

### LINKED ISSUE #164: Can only select annotations of the same type
**Describe the bug**

If the current active annotation is a spline, then the only way to select a paintbrush annotation is to first make a new paintbrush annotation - then you can select the old one by cycling with Ctrl-arrowkeys or with Ctrl-a then click. Or vice versa, if the active annotation is paintbrush and you want to select a spline.

**To Reproduce**

1.  Draw a brushstroke
2.  Make a new annotation
3.  Select the spline tool and draw a spline
4.  Try to select the original brushstroke, either by Ctrl-arrowkeys or Ctrl-a then clicking on it

**Expected behavior**

Brush annotation becomes active.

### PR DESCRIPTION
**Pull request by philipjackson**
# Description

Before we could only select splines when a spline was active, and only select brushstrokes when paintbrush was active, now click-to-select can select anything regardless of which type annotation is active (Ctrl-arrows still cycles through annotations of the same type).

Also re-wrote the code for detecting brushstroke-clicks, so it no longer gets false negatives when you click in between two widely spaced brush coordinate points (which can happen if the brushstroke was drawn with a rapid mouse movement).

Had to move some code out of SplineCanvas and PaintbrushCanvas and into the Annotations class to make this work.

closes #164 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Looking really good... but: when I ctrl+A and then click a paintbrush, I am still in click and select mode... when I select a spline, I jump into spline mode! I don't know which is better but could we make them act the same?

**Comment by philipjackson** [comment]
Update: as discussed, `mode` is no longer an independent state in `SplineCanvas` and `PaintbrushCanvas`, it's been lifted up into `ui` now. I also removed `magic` from it, because `magicspline` is a tool, not a mode, and we're already passing the tool in as the `activeTool` prop. Also removed the `isActive` state from `SplineCanvas` since that too was already determined by props.

**Comment by cooper667** [comment]
Not sure if it's covered in the new UI, but some sort of button to toggle/show the mode along with the shortcut key might be useful?

**Review by cooper667 — APPROVED** [review]
it's better AND it's less code. My 2 favourite things

**Review by ChasNelson1990 — APPROVED** [review]

**Pull request merged**
