### PR TITLE
fix: prevent default of key shortcuts we override

### PR DESCRIPTION
**Pull request by cooper667**
as described. Means zoom looks pretty.

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
I presume we're ignoring BrowserStack for now?

**Comment by cooper667** [comment]
> Hmmm... doesn't seem to work for Chrome on Linux...?

Is that doing ctrl + ?

**Review by joshuajames-smith — DISMISSED** [review]
Working for me on macOS/safari and macOS/chrome!

**Review by ChrisBaidoo — DISMISSED** [review]

**Comment by ChasNelson1990** [comment]
> Is that doing ctrl + ?

Yep.

**Comment by ChasNelson1990** [comment]
Also tested on Firefox on Linux, `ctrl` `+` causes a browser zoom not a gliff zoom

**Review by joshuajames-smith — APPROVED** [review]

**Review by ChasNelson1990 — APPROVED** [review]

**Pull request merged**
