### PR TITLE
Dependabot batch

### PR DESCRIPTION
**Pull request by ChasNelson1990**
All the minor dependabots, scripted PR

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
@cooper667 any idea how to solve this no-unsafe-call error - in my editor everything is typed lol.

**Comment by cooper667** [comment]
image

It's failing on this anyway so we should maybe rethink it...

**Comment by cooper667** [comment]
```    var fileURL = URL.createObjectURL(response);
    if (navigator.userAgent.indexOf("Chrome") != -1 || navigator.userAgent.indexOf("Firefox") != -1){
        let win = window.open(fileURL, '_blank');                        
    } else { //Safari & Opera iOS
        window.location.href = fileURL;
    }```
    
    
Something like this...

**Comment by cooper667** [comment]
It's only for IE which I'm not sure we care about?

**Comment by cooper667** [comment]
image
oh no

**Comment by ChasNelson1990** [comment]
Its not as bad as it looks

**Review by philipjackson — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Review by philipjackson — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Review by cooper667 — APPROVED** [review]

**Pull request merged**
