### PR TITLE
Minor changes to make this usable in an alpha project

### LINKED ISSUE #49: Add paintbrush cursor
Currently we use a standard CSS pointers for painting. In the previous version we used a preview of the brush and the size.

### PR DESCRIPTION
**Pull request by ChasNelson1990**
# Description

Mostly UI changes, including making the brush radius a slider control and adding a paintbrush cursor.

closes #49

# Dependency changes

None

# Testing

N/A

# Documentation

New user documentation coming soon.

# Migrations (if applicable)

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] ~New migrations have been committed~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
There's a couple of lint errors that I'm not sure how to solve - any ideas?

**Review by philipjackson — APPROVED** [review]

**Review by ChrisBaidoo — COMMENTED** [review]
Looks good.
Do we want to show the "cursor: not-allowed" when we are erasing?

**Comment by ChasNelson1990** [comment]
> Looks good.
> Do we want to show the "cursor: not-allowed" when we are erasing?

I actually didn't change this... but I agree... but also... is there a better one?

**Comment by ChrisBaidoo** [comment]
> > Looks good.
> > Do we want to show the "cursor: not-allowed" when we are erasing?
> 
> I actually didn't change this... but I agree... but also... is there a better one?

Hide it and just show the circle just like we do when we're painting, maybe?

**Review by ChrisBaidoo — APPROVED** [review]

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
