### PR TITLE
feat: View annotations

### LINKED ISSUE #735: View Single Annotations
## Problem

Relates to https://github.com/gliff-ai/roadmap/issues/3.
Our users currently do not have a way to view a single assignees annotations on a single image.

## Solution

**ANNOTATE** has a slightly different UI for the view annotation feature.
The top-left toolbar is paired down, and consists of: `Select` tool, `Select Users` tool, `Annotation Layers` tool and `Background Settings` tool (which has a sub-toolbar, and consists of : `Brightness` tool, `Contrast` tool, `Channels` tool and `Annotation Transparency` tool).

View Annotations - Annotate – Main Screen

Clicking the `Select Users` icon opens this dialogue. The `View` button is greyed out (disabled) if there is no changes, and will become green is a user has been changed. This dialogue works under the assumption that the confirmation will reload the page to display the new user(s).

View Annotations - Annotate – Select Users Dialogue  open w- no changes

Clicking the `Annotations Layers` icon opens this dialogue. It become apparent from a UX-persecptive that: 1) it might be too hard to select annotations with the `Select` tool if annotations are stacked on top of one another; and 2) it offers a way to easily glance at the type of annotations, and view labels. Focusing on the UI principal of reducing visual clutter, the user switches between either users annotation by clicking the user's name container or the `Switch Users` icon.

View Annotations - Annotate – Select Users Dialogue  open w- expanded drawer

View Annotations - Annotate – Select Users Dialogue  open

## Considered Alternatives

N/A

### PR DESCRIPTION
**Pull request by philipjackson**
## Description

Adds a readonly mode to ANNOTATE. To use is, set the `readonly` prop to `true`, pass the initial `annotationsObject` to display (chosen by the user in CURATE with the View Annotations dialog) as `annotationsObject`, and pass the full `username -> annotationsObject` dictionary as `userAnnotations` so that annotations by other users can also be displayed. Readonly mode removes all the toolbar buttons except Select and Background toolbox, and adds the Users tool, which lets you display the annotations of a different user, and the Layers tool, which lets you see all the layers (annotations) in a list, and displays their labels and selects them when clicked.

closes #735 

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [ ] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
> This pull request **introduces 4 alerts**

want to do these and pull main before we review?

**Comment by philipjackson** [comment]
> want to do these and pull main before we review?

It is done

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
Are we able to create an example? E.g. could we add an example at localhost:3000/readonly that shows the heart picture and a read only annotation? This could also be added as a unique Percy test (no need for BrowserStack)?

**Comment by philipjackson** [comment]
> Are we able to create an example? E.g. could we add an example at localhost:3000/readonly that shows the heart picture and a read only annotation? This could also be added as a unique Percy test (no need for BrowserStack)?

Done and done (although I don't remember how to make the Percy test skip browserstack?)

**Review by cooper667 — APPROVED** [review]

**Review by joshuajames-smith — CHANGES_REQUESTED** [review]
- [x] The `Background Settings` toolbox remains open even when the `Select a User` or `Annotation Layers` dialogues are open. Can this secondary toolbar close when either of these dialogues are selected?

Screenshot 2022-06-13 at 13 17 30

- [ ] ^ The select field appears to believe this box is for passwords? Can this be disabled?
- [ ] ^ The `cross` icon has a large indent on the right? - wrong positioning. @ChrisBaidoo fixed this?

- [ ] Can the `Select Annotations` tool remain active after a new annotation has been selected? This would allow the user to click several annotations in a row without having to click the `Selection Annotations` tool first east time - having this tool always selected would also improve the UX.

Screenshot 2022-06-13 at 13 23 56 Screenshot 2022-06-13 at 13 33 10

- [x] ^ The styling of the `Annotations Layers` is not as originally design. Might be one for @ChrisBaidoo to pick up on? It is functional for now atleast - this could be made into another issue.

**Comment by philipjackson** [comment]
> The Background Settings toolbox remains open even when the Select a User or Annotation Layers dialogues are open. Can this secondary toolbar close when either of these dialogues are selected?

This is fixed by the style PR I made: https://github.com/gliff-ai/style/pull/226

>  The select field appears to believe this box is for passwords? Can this be disabled?

The only reason I can imagine your browser is doing this is because I set the label to "Username" - I've changed it to "User", does that fix it?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by joshuajames-smith — APPROVED** [review]

**Review by ChasNelson1990 — APPROVED** [review]

**Pull request merged**
