### PR TITLE
feat: Download paintbrush annotations as tiff

### LINKED ISSUE #128: DOWNLOAD
**Is your feature request related to a problem? Please describe.**

Currently we can't export our annotations (paintbrushes or splines) in common formats.

**Describe the solution you'd like**

A tool to export gliff.ai annotations as either: ND uint8 label-indexed TIFFs (with index: label mapping as an accompanying JSON?) or labelled XY(Z) spline nodes as JSON. (Happy to have a call about that if that's not clear)

**Describe alternatives you've considered**

N/A

**Additional context**

The tool should probably be a separate repository as we will want to make this functionality available in both ANNOTATE and CURATE, i.e. this is the opposite of UPLOAD.

### PR DESCRIPTION
**Pull request by SilviaZeta**
# Description

Adds:
- download paintbrush annotations as tiff;
- fix bug with brush radius not resizing at window resize.

Note: paintbrush annotations are stored as vectors; atm we are looping though all pairs of [x,y] points and draw capsules with radius equal to the brush radius stored for the given annotation.

What's not working:
- ~when re-uploaded, the tiff export looks pixellated (based on the dimension of image annotated)~;
- ~exported as grayscale, so distinct annotation objects are hard to distinguish~ (note: tried to export as "palette color" tiff, but it required setting tag 320 (i.e., colourMap), which does not seem to be supported by the utif package, so in the end went for a "full color" tiff). 

closes #128 (download as tiff only, while missing export of annotation data as .json)
coses #136

# Dependency changes
utif package (temporary, as the code will be moved to its own repo).

# Testing
No

# Documentation
N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by philipjackson** [comment]
I've noticed that if you draw brush strokes that extend over the edges of the image then when you save the annotation, the parts that went over the edge seem to wrap around and reappear at the other side.

**Comment by SilviaZeta** [comment]
> I've noticed that if you draw brush strokes that extend over the edges of the image then when you save the annotation, the parts that went over the edge seem to wrap around and reappear at the other side.

Yes, that too! Though I think it would make more sense to change how we store the data (i.e., don't store any data outside of the background image, rather than to apply some selection at export.

**Comment by ChasNelson1990** [comment]
> * fix bug with brush radius not resizing at window resize.

Do you mean when zooming in on the image? Weird, I thought somebody already fixed that.

**Comment by ChasNelson1990** [comment]
> * when re-uploaded, the tiff export looks pixellated (based on the dimension of image annotated);

TBH, we should probably make our brushes pixelised? One for discussion.

**Comment by SilviaZeta** [comment]
> > * fix bug with brush radius not resizing at window resize.
> 
> Do you mean when zooming in on the image? Weird, I thought somebody already fixed that.

Yes, we fixed it for zooming in (image scaling), but not for resizing the canvas area, which happen when resizing the window or viewport, see #136; image-to-canvas scaling).

**Comment by ChasNelson1990** [comment]
> This pull request **introduces 1 alert** when merging [de946b0](https://github.com/gliff-ai/annotate/commit/de946b048bc01cfd0e84c0c7d4eb2d0d2ca48cad) into [56155d7](https://github.com/gliff-ai/annotate/commit/56155d722d77704b151a6189165966b202ecf9f9) - [view on LGTM.com](https://lgtm.com/projects/g/gliff-ai/annotate/rev/pr-50d27547eb523100d1de3c45840e2dd67d534e1e)
> 
> **new alerts:**
> 
> * 1 for Unused variable, import, function or class

It's a tiny alert but maybe worth fixing?

**Comment by SilviaZeta** [comment]
> > This pull request **introduces 1 alert** when merging [de946b0](https://github.com/gliff-ai/annotate/commit/de946b048bc01cfd0e84c0c7d4eb2d0d2ca48cad) into [56155d7](https://github.com/gliff-ai/annotate/commit/56155d722d77704b151a6189165966b202ecf9f9) - [view on LGTM.com](https://lgtm.com/projects/g/gliff-ai/annotate/rev/pr-50d27547eb523100d1de3c45840e2dd67d534e1e)
> > **new alerts:**
> > 
> > * 1 for Unused variable, import, function or class
> 
> It's a tiny alert but maybe worth fixing?

Actually, this seems to refer to an older version of the code?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
