### PR TITLE
feat: standardise repo labels 🔨

### PR DESCRIPTION
**Pull request by joshuajames-smith**
## Description

Add labels.yml list and apply-labels.yml action for consistent labels between repos.

### CODE REVIEW

**Review by ChasNelson1990 — APPROVED** [review]

**Comment by joshuajames-smith** [comment]
@ChasNelson1990 I made a commit to delete labeler.yml but after looking more closely in your commit to add them, assuming you actually want to keep them?

**Comment by ChasNelson1990** [comment]
> @ChasNelson1990 I made a commit to delete labeler.yml but after looking more closely in your commit to add them, assuming you actually want to keep them?

Yes please

**Comment by joshuajames-smith** [comment]
`Azure Static Web Apps CI/CD / Build and Deploy Job (pull_request)` workflow failing?

**Review by ChasNelson1990 — APPROVED** [review]

**Comment by ChasNelson1990** [comment]
> `Azure Static Web Apps CI/CD / Build and Deploy Job (pull_request)` workflow failing?

It can only spin up a max of three over all PRs, no worries.

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
