### PR TITLE
feat: style spline toolbox

### LINKED ISSUE #270: Spline Submenu Styling
**Is your feature request related to a problem? Please describe.**

The new spline Submenu needs new icon designs, currently just using placeholders:
image

**Describe the solution you'd like**

We need icons for:
- [x] Spline
- [x] Lasso Spline
- [x] Magic Spline
- [x] Close Active Spline
- [x] Fill Spline
- [x] Convert Spline to Paintbrush Annotation

**Describe alternatives you've considered**

None

**Additional context**

None

### PR DESCRIPTION
**Pull request by ChasNelson1990**
# Description

Adds new icons for the fill button (paintbrush popover) and all the new spline buttons (spline popover).

closes #270

# Dependency changes

None

# Testing

None

# Documentation

None

# Migrations (if applicable)

N/A

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by philipjackson — DISMISSED** [review]

**Comment by SilviaZeta** [comment]
Keybindings for spline needs updating: 'close active spline' still works on ctrl+C and L opens the 'annotation label' popover. Or should this be part of another PR?

**Review by SilviaZeta — APPROVED** [review]

**Review by cooper667 — DISMISSED** [review]

**Comment by ChrisBaidoo** [comment]
For some reason we have two fill icons now...
Screenshot 2021-07-29 at 15 40 50

**Comment by ChasNelson1990** [comment]
> For some reason we have two fill icons now...

Looks like we mis-pulled in your style commits - wanna make a commit to correct it?

**Comment by ChrisBaidoo** [comment]
@ChasNelson1990 not sure how to resolve this conflict

**Review by ChrisBaidoo — APPROVED** [review]

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
