### PR TITLE
fix: support cmd key on click

### LINKED ISSUE #685: Force-add spline does not work on Mac
## Bug Description

You should be able to add a node in between two other connected nodes of a spline with Ctrl+click on Windows/Linux or Cmd+click on Mac but the latter doesn't work.

## To Reproduce

Steps to reproduce the bugs' behaviour:

1. Go to a Mac
2. Open a Browser
3. Go to ANNOTATE
4. Make a spline
5. Try to force add a new one

## Expected Behaviour

A node is inserted into the middle of the existing spline.

## System Info:

- Operating System: macOS
- Browser: any

### PR DESCRIPTION
**Pull request by cooper667**
Fixes #685

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Have changed reviewers to people on Macs to test properly. Code LGTM though.

**Comment by cooper667** [comment]
It works on mac, my question would be does it still work on non Mac 😁

**Comment by philipjackson** [comment]
> It works on mac, my question would be does it still work on non Mac grin

I can still CTRL-click to insert spline points on Linux.

**Review by joshuajames-smith — CHANGES_REQUESTED** [review]
Using `CMD` to add a point works for me! But if I'm holding `CMD` to add a spline point and drag, it doesn't visualise until I let go off the click? Could the initial click show the point even if the user is trying to also drag to move the point in the same click? This would give better feedback that a point has been added and the point is being moved!

https://user-images.githubusercontent.com/83074763/166446187-e1b8c9f8-588e-4235-8421-e7158f0bd510.mov

**Comment by cooper667** [comment]
> Using `CMD` to add a point works for me! But if I'm holding `CMD` to add a spline point and drag, it doesn't visualise until I let go off the click? Could the initial click show the point even if the user is trying to also drag to move the point in the same click? This would give better feedback that a point has been added and the point is being moved!
> 
>  Add.Spline.Point.Demonstration.mov

Yea but in another PR 😁

**Review by joshuajames-smith — APPROVED** [review]

**Review by ChrisBaidoo — APPROVED** [review]

**Pull request merged**
