### PR TITLE
build: Add Vite

### LINKED ISSUE #127: Improve Webpack to decrease bundle size
```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (293 KiB)
      main.js


WARNING in webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

### PR DESCRIPTION
**Pull request by cooper667**
Remove Webpack, add Vite, fix test runner, update deps, change a couple imports so they match the other styles. Make eslint match other repos.

fix #127  (3mb -> 500k)

### CODE REVIEW

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
The minimap icon is missing for me? Chromium on Arch Linux.

**Comment by ChasNelson1990** [comment]
Interesting... seems Percy isn't running. I thought it wasn't needed to explicitly add it to the actions anymore but maybe I misunderstood... one for Monday.

**Comment by cooper667** [comment]
> The minimap icon is missing for me? Chromium on Arch Linux.

fixed

**Review by ChasNelson1990 — DISMISSED** [review]

**Comment by ChasNelson1990** [comment]
`npm run serve` doesn't seem to work like it used to? I.e. if I run it, it serves something and says its successsful - it doesn't work so I build it and it falls over and tells me why. Webpack used to still tell us about problems with `serve`. Also, why don't `serve` and `build:example` use `npx`?

**Comment by ChasNelson1990** [comment]
And it seems the vite build misses things that webpack wouldn't, i.e. a load of "not imported" issues where ignored but of course prevent the page loading.

**Comment by cooper667** [comment]
I think it's a combination of https://vitejs.dev/guide/why.html#slow-server-start and it not checking types?

It should use npx I think

**Comment by ChasNelson1990** [comment]
Any idea why adding:
```
  leftToolbar: {
    display: "flex",
    flexDirection: "column",
    top: "108px",
    left: "18px",
    bottom: "18px",
    width: "63px",
    zIndex: 100,
    justifyContent: "space-between",
    position: "fixed",
  },
```
after `displayContainer` in the styles object and making no other changes causes all classnames to be unfindable? Seems to break the typing but as the type is `typeof styles` it shouldn't lol.

**Comment by ChasNelson1990** [comment]
> I think it's a combination of https://vitejs.dev/guide/why.html#slow-server-start and it not checking types?

Do we not want it to type check?

> It should use npx I think

Not explicitly, so if I have a global version of vite won't it use that first?

**Comment by cooper667** [comment]
> > I think it's a combination of https://vitejs.dev/guide/why.html#slow-server-start and it not checking types?
> 
> Do we not want it to type check?

We can add another sctipt to run in parallel, but I just rely on my ide for it

**Comment by ChasNelson1990** [comment]
> I just rely on my ide for it

From experience, relying on people noticing squiggles seems unsafe. I realise the lint should catch many type errors too but from experience today alone, lint does not catch some and if vite doesn't catch them either then you end up debugging something quite simple through the browser console, rather than just being told the problem in the first place?

**Comment by cooper667** [comment]
> > I just rely on my ide for it
> 
> From experience, relying on people noticing squiggles seems unsafe. I realise the lint should catch many type errors too but from experience today alone, lint does not catch some and if vite doesn't catch them either then you end up debugging something quite simple through the browser console, rather than just being told the problem in the first place?

changed

**Comment by cooper667** [comment]
> Any idea why adding:
> 
> ```
>   leftToolbar: {
>     display: "flex",
>     flexDirection: "column",
>     top: "108px",
>     left: "18px",
>     bottom: "18px",
>     width: "63px",
>     zIndex: 100,
>     justifyContent: "space-between",
>     position: "fixed",
>   },
> ```
> 
> after `displayContainer` in the styles object and making no other changes causes all classnames to be unfindable? Seems to break the typing but as the type is `typeof styles` it shouldn't lol.

```js
  leftToolbar: {
    display: "flex",
    flexDirection: "column" as const,
    top: "108px",
    left: "18px",
    bottom: "18px",
    width: "63px",
    zIndex: 100,
    justifyContent: "space-between",
    position: "fixed" as const,
  },
 ```

**Comment by ChasNelson1990** [comment]
Why?

**Comment by cooper667** [comment]
> Why?

Based on what we'd done above.

I _assume_ the values for those keys should be imported consts/enums from Material UI rather than strings?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Pull request merged**
