### PR TITLE
feat: add paintbrush canvas

### PR DESCRIPTION
**Pull request by cooper667**
Adds Paintbrush tool

- Uses 2 canvases, one for drawing on and one for storing the actaul drawing
- Changes to the annotation structure to allow us to store individual strokes with the relevant parameters

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Where's the PR details?!

**Comment by cooper667** [comment]
> Where's the PR details?!

@ChrisBaidoo is working on it, it's just because I converted the existing draft!

**Comment by cooper667** [comment]
(While I run prettier on all the files he touched)

**Comment by ChasNelson1990** [comment]
> * Make basecanvas mouseevents a bit more generic and attach them all

Check out my mouse interactions for the minimap I might have done a bit of this for you?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by ChasNelson1990 — APPROVED** [review]

**Review by philipjackson — DISMISSED** [review]

**Review by SilviaZeta — DISMISSED** [review]

**Review by ChrisBaidoo — APPROVED** [review]

**Review by ChasNelson1990 — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Review by philipjackson — APPROVED** [review]

**Pull request merged**
