### PR TITLE
feat: Import popover from style

### PR DESCRIPTION
**Pull request by ChrisBaidoo**
## Description

- Import popover component from style.
- Remove makeStyles 

closes gliff-ai/style#716

- [x] I have read the gliff.ai Contribution Guide.
- [x] I have requested to **pull a branch** and not from main.
- [x] I have checked all commit message styles match the requested structure.
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have performed a self-review of my own code.
- [ ] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Comment by joshuajames-smith** [comment]
@ChrisBaidoo has the style been applied to any UI element? not sure if im missing it?

**Comment by philipjackson** [comment]
Is the pinch to zoom stuff supposed to be in this PR? If not then I'm still happy to approve and merge so long as it's tested and working, since stripping it out into a separate PR could be a lot of work.

**Comment by joshuajames-smith** [comment]
@ChrisBaidoo a few things failing, including staging but not because we reached staging limit?

**Comment by ChrisBaidoo** [comment]
> @ChrisBaidoo a few things failing, including staging but not because we reached staging limit?

its because we needed to get this PR in STYLES(https://github.com/gliff-ai/style/pull/173#pullrequestreview-960138448) merged first so that it could be used here 😀

**Review by joshuajames-smith — APPROVED** [review]

**Pull request merged**
