### PR TITLE
feat: paintbrush splodge test

### LINKED ISSUE #410: Annotation system tests
## Describe the test

We need a series of system tests and visual tests, using BrowserStack Automate, Selenium and Percy Snapshot (@joshuajames-smith), for each annotation type:

- [x] paintbrush
- [x] eraser
- [x] fill  (covered by unittest #407)
- [x] normal spline
- [x] lasso spline
- [x] close active spline (covered by unittest #407)
- [x] convert spline to paintbrush (covered by unittest #407)
- [x] bounding box

*NOTE: I recommend splitting this issue into one for each annotation for easier tracking of progress but will leave this to @philipjackson ***

### PR DESCRIPTION
**Pull request by philipjackson**
## Description

First working attempt at a Selenium/Percy/BrowserStack paintbrush canvas test. Currently just draws a splodge at a fixed location on the canvas. Unfortunately I've not actually found a way to tell Selenium things like "move mouse to (500,500), left mouse down, move to (700,500), left mouse up". Instead, it works by injecting JS code that selects the paintbrush interaction canvas and creates and dispatches events from it. This is further downstream than we'd like, because it can't test that the right canvas hears the mouse and that the right mouse handlers get fired, because we're almost calling those handlers directly (probably could actually do that and it'd be the same, since the current method specifies both the canvas and the event type (`mousedown` in this case)).

I've been running it by running ANNOTATE standalone in one tab, and `npx percy exec -- jest -c jest.e2e.config.js --no-colors` in another. `npm test` will pick it up but fails because it doesn't start Percy; maybe should exclude `__tests__/e2e` for `npm test`? I've added the line `"test:e2e": "percy exec -- jest -c jest.e2e.config.js --no-colors",` in package.json, and that does seem to pick it up and work, but still needs the server running locally of course.

Also: had to `npm install @babel/plugin-transform-runtime` and add `"env": {"test": {"plugins": ["@babel/plugin-transform-runtime"]}}` in babel.config.js after merging in from main or else the test broke.

closes #410 

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New migrations have been committed
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] If appropriate, I have bumped any version numbers

### CODE REVIEW

**Comment by ChasNelson1990** [comment]
Why can't you use Selenium click functions again? E.g. https://www.lambdatest.com/blog/selenium-click-button-with-examples/ The click and hold example 2/3 of the way down looks particularly useful?

**Comment by cooper667** [comment]
> Why can't you use Selenium click functions again? E.g. https://www.lambdatest.com/blog/selenium-click-button-with-examples/ The click and hold example 2/3 of the way down looks particularly useful?

They are called on elements, so you select a button then `.click` etc

**Comment by philipjackson** [comment]
> Why can't you use Selenium click functions again? E.g. https://www.lambdatest.com/blog/selenium-click-button-with-examples/ The click and hold example 2/3 of the way down looks particularly useful?

Yeah, the command on that page that _would_ be useful is `moveByOffset`, but it doesn't seem to be a thing in JS Selenium, only Java (this page) and Python; the other commands all just target elements and don't allow you to specify coordinates, which we need to clicking in different places on the canvas. Craig did find [this link](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/lib/input_exports_Actions.html) though which might allow me to use coordinates in JS Selenium without `executeScript`, no luck yet but I'll see what I can do next week.

**Comment by philipjackson** [comment]
The test runs fine locally but fails in the GH action with the following error:

```
    WebDriverError: unknown error: Chrome failed to start: crashed.
      (unknown error: DevToolsActivePort file doesn't exist)
      (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

This seems to be a common problem, with lots of people fixing it by passing certain flags to Chrome:
https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t
https://github.com/heroku/heroku-buildpack-google-chrome/issues/46
https://stackoverflow.com/questions/58500512/showing-error-unknown-error-devtoolsactiveport-file-doesnt-exist-its-elec
https://stackoverflow.com/questions/58997940/selenium-grid-devtoolsactiveport-file-doesnt-exist-unknown-error-chrome-fail

I don't *think* we can do that "from the outside" of Craig's test harness, so today I've been hard-coding those into [jest-browserstack-automate](https://github.com/gliff-ai/jest-browserstack-automate) and syncing it with ANNOTATE the usual way via `npm pack`, and then testing the GH action locally using [act](https://github.com/nektos/act) to see if the error goes away. So far, it has not. It's unclear to me though whether `npm i gliff-ai-jest-browserstack-automate-5.0.1.tgz` would result in the package being used in act - I think it should, since package.json will specify it, but I couldn't confirm that via `console.log`s.

One thing I did find while making act work is that there's a typo in lint-build-test.yml - the `needs` field in `publish` job is case sensitive, so it should be `Test` not `test`. This was also the case in MANAGE, and probably all the other repos since this file gets copied around.

The changes I made to jest-browserstack-automate were at line 77 in index.js - I changed it to this:
```
    const options = new chrome.Options();
    options.addArguments("--no-sandbox");
    options.addArguments("--headless");
    options.addArguments("--disable-dev-shm-usage");
    options.addArguments("--remote-debugging-port=9222");

    return new webdriver.Builder()
      .usingServer(BROWSERSTACK_URL)
      .withCapabilities(baseCapabilities)
      .setChromeOptions(options)
      .build();
  };
```

This may or may not be the right way to do it. I'm still not sure if options and capabilities are actually different things in Selenium; if not, then this is probably unnecessary since jest-browserstack-automate already lets us pass capabilities in (though this didn't seem to fix it either).

**Comment by cooper667** [comment]
>>>I've been running it by running ANNOTATE standalone in one tab, and npx percy exec -- jest -c jest.e2e.config.js --no-colors in another. npm test will pick it up but fails because it doesn't start Percy; maybe should exclude __tests__/e2e for npm test? I've added the line "test:e2e": "percy exec -- jest -c jest.e2e.config.js --no-colors", in package.json, and that does seem to pick it up and work, but still needs the server running locally of course.

I've changed it so __tests__ is now outside /src, so the "regular" tests don't try to run the e2e ones (I had trouble with Jest exclude globs on Manage, this is easier

**Comment by cooper667** [comment]
> The test runs fine locally but fails in the GH action with the following error:
> 
> ```
>     WebDriverError: unknown error: Chrome failed to start: crashed.
>       (unknown error: DevToolsActivePort file doesn't exist)
>       (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
> ```
> 
> This seems to be a common problem, with lots of people fixing it by passing certain flags to Chrome: https://stackoverflow.com/questions/50642308/webdriverexception-unknown-error-devtoolsactiveport-file-doesnt-exist-while-t [heroku/heroku-buildpack-google-chrome#46](https://github.com/heroku/heroku-buildpack-google-chrome/issues/46) https://stackoverflow.com/questions/58500512/showing-error-unknown-error-devtoolsactiveport-file-doesnt-exist-its-elec https://stackoverflow.com/questions/58997940/selenium-grid-devtoolsactiveport-file-doesnt-exist-unknown-error-chrome-fail
> 
> I don't _think_ we can do that "from the outside" of Craig's test harness, so today I've been hard-coding those into [jest-browserstack-automate](https://github.com/gliff-ai/jest-browserstack-automate) and syncing it with ANNOTATE the usual way via `npm pack`, and then testing the GH action locally using [act](https://github.com/nektos/act) to see if the error goes away. So far, it has not. It's unclear to me though whether `npm i gliff-ai-jest-browserstack-automate-5.0.1.tgz` would result in the package being used in act - I think it should, since package.json will specify it, but I couldn't confirm that via `console.log`s.
> 
> One thing I did find while making act work is that there's a typo in lint-build-test.yml - the `needs` field in `publish` job is case sensitive, so it should be `Test` not `test`. This was also the case in MANAGE, and probably all the other repos since this file gets copied around.
> 
> The changes I made to jest-browserstack-automate were at line 77 in index.js - I changed it to this:
> 
> ```
>     const options = new chrome.Options();
>     options.addArguments("--no-sandbox");
>     options.addArguments("--headless");
>     options.addArguments("--disable-dev-shm-usage");
> 
>     return new webdriver.Builder()
>       .usingServer(BROWSERSTACK_URL)
>       .withCapabilities(baseCapabilities)
>       .setChromeOptions(options)
>       .build();
>   };
> ```
> 
> This may or may not be the right way to do it. I'm still not sure if options and capabilities are actually different things in Selenium; if not, then this is probably unnecessary since jest-browserstack-automate already lets us pass capabilities in (though this didn't seem to fix it either).

This is likely because it's trying to start Chrome within GH actions, rather than use the remote Browserstack browser. I've added the GH action runner from Manage which should pull in the secrets and prevent this

**Comment by cooper667** [comment]
It runs in Automate!

However all the offsets seem wrong when running there compared to local so it looks like drunk scribbles 😁 

https://user-images.githubusercontent.com/3502798/143838182-3d6bb257-7860-4a9f-a83c-328b6768f7d5.mp4

**Comment by cooper667** [comment]
So, this is 1 test that does a bunch of drawings and then tests them all with a Percy screenshot. We probably want new issues for anything that we want covering with smaller tests (Undo/redo springs to mind)

**Comment by cooper667** [comment]
> It runs in Automate!
> 
> However all the offsets seem wrong when running there compared to local so it looks like drunk scribbles 😁
> 
>  video-b0db34790a2be0376fc1ad60daef8bf71f3d9010.mp4

this was fixed by pausing between each selenium instruction

**Review by cooper667 — APPROVED** [review]

**Review by SilviaZeta — APPROVED** [review]

**Pull request merged**
