### PR TITLE
fix!: Upgrade @gliff-ai/style to the latest version

### PR DESCRIPTION
**Pull request by SilviaZeta**
## Description
- @gliff-ai/style to 16.0.0
- remove deprecated prop `noPadding` from `Card` component
- fix esconfig so that all .tsx and .ts files inside `/src/` are linted

## Checklist:

Put an `x` in the boxes that apply to this pull request (you can also fill these out after opening the pull request). If you're unsure about any of these, don't hesitate to leave a comment on this pull request!

- [ ] I have read the gliff.ai Contribution Guide.
- [x] I have requested to **pull a branch** and not from main.
- [ ] I have checked all commit message styles match the requested structure.
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have performed a self-review of my own code.
- [x] I have assigned **3 or less** reviewers.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] My changes generate no new warnings.
- [ ] I have made corresponding changes to the documentation.
- [ ] New database changes have been committed.
- [ ] If appropriate, I have bumped any version numbers.

### CODE REVIEW

**Review by Kinukeo — DISMISSED** [review]

**Review by ChasNelson1990 — CHANGES_REQUESTED** [review]
Do we also need to fix the lint and prettier commands in package.json?

**Comment by SilviaZeta** [comment]
> Do we also need to fix the lint and prettier commands in package.json?

What's wrong with those? Sorry, I don't see it.

**Comment by ChasNelson1990** [comment]
> What's wrong with those? Sorry, I don't see it.

Should https://github.com/gliff-ai/annotate/blob/ed4e6c4988173ae11195e59c55aeb73c3292fa70/package.json#L18 (and the prettier equivalent) go from `src` to `src/**/**/**/*_.ts*` too?

**Comment by SilviaZeta** [comment]
> > What's wrong with those? Sorry, I don't see it.
> 
> Should
> 
> https://github.com/gliff-ai/annotate/blob/ed4e6c4988173ae11195e59c55aeb73c3292fa70/package.json#L18
> (and the prettier equivalent) go from `src` to `src/**/**/**/*_.ts*` too?

adding `src/**/**/**/*.ts*` doesn't seem to make a difference and all the .ts and .tsx files in the subfolders of src are linted.

**Comment by ChasNelson1990** [comment]
> adding `src/**/**/**/*.ts*` doesn't seem to make a difference and all the .ts and .tsx files in the subfolders of src are linted.

What about prettier. Because if that's the case then the linter should have caught the hanging prop when run on GitHub, no?

**Comment by SilviaZeta** [comment]
> > adding `src/**/**/**/*.ts*` doesn't seem to make a difference and all the .ts and .tsx files in the subfolders of src are linted.
> 
> What about prettier. Because if that's the case then the linter should have caught the hanging prop when run on GitHub, no?

Yes, you are right! So it looks like the file not being linted is not the issue here, because the file with the deprecated prop was only 2 levels down from src and the linter catches some other warnings on that exact same file. Instead, it looks like we are missing an eslint rule for catching that error?

**Review by ChasNelson1990 — APPROVED** [review]

**Review by Kinukeo — APPROVED** [review]

**Pull request merged**
